"""Tests for models.py

Auto-generated by scan_and_test.py -- covers importability
and pure functions discovered via AST analysis.
"""

import importlib.util
import sys
import tempfile
from pathlib import Path

import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _load_module():
    """Import models by file path."""
    filepath = PROJECT_ROOT / "core/models.py"
    spec = importlib.util.spec_from_file_location("models", filepath)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    # Patch sys.argv to prevent argparse from firing
    old_argv = sys.argv
    sys.argv = ["test"]
    try:
        spec.loader.exec_module(mod)
    except SystemExit:
        pass
    finally:
        sys.argv = old_argv
    return mod


@pytest.fixture(scope='module')
def mod():
    """Load the module once for all tests."""
    return _load_module()


class TestImport:
    def test_module_loads(self, mod):
        """Module imports without error."""
        assert mod is not None


class TestFunctions:
    def test_generate_id_exists(self, mod):
        """generate_id is callable."""
        assert hasattr(mod, "generate_id")
        assert callable(getattr(mod, "generate_id"))

    def test_generate_id_runs(self, mod):
        """generate_id executes without error."""
        result = mod.generate_id()
        # Function returned without raising
        assert result is not None or result is None

