"""Shell completion script renderer.

This module emits small, self-contained completion scripts for codegraphx.
PowerShell support is first-class since that is the primary development shell
on Windows. Bash/zsh/fish get a minimal implementation that completes the
top-level command names.
"""

from __future__ import annotations

import typer


SUPPORTED_SHELLS = ("powershell", "pwsh", "bash", "zsh", "fish")


def render_completion_script(shell: str, app_name: str, commands: list[str]) -> str:
    shell_lc = shell.strip().lower()
    if shell_lc in {"powershell", "pwsh"}:
        return _render_powershell(app_name, commands)
    if shell_lc == "bash":
        return _render_bash(app_name, commands)
    if shell_lc == "zsh":
        return _render_zsh(app_name, commands)
    if shell_lc == "fish":
        return _render_fish(app_name, commands)
    raise typer.BadParameter(
        f"unsupported shell '{shell}'. Expected one of: {', '.join(SUPPORTED_SHELLS)}"
    )


def _render_powershell(app_name: str, commands: list[str]) -> str:
    joined = ", ".join(f"'{c}'" for c in commands)
    # Plain ASCII only per project policy; no smart quotes, no emojis.
    return f"""# {app_name} PowerShell completion
# Generated by `{app_name} completions powershell`.
# Source from your $PROFILE, e.g.:
#   {app_name} completions powershell | Out-File -Encoding utf8 $PROFILE.CurrentUserAllHosts

Register-ArgumentCompleter -Native -CommandName {app_name} -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = @({joined})
    $tokens = $commandAst.CommandElements
    $tokenCount = $tokens.Count

    if ($tokenCount -le 1 -or ($tokenCount -eq 2 -and $wordToComplete)) {{
        $commands |
            Where-Object {{ $_ -like "$wordToComplete*" }} |
            ForEach-Object {{
                [System.Management.Automation.CompletionResult]::new(
                    $_, $_, 'ParameterValue', $_
                )
            }}
        return
    }}

    # For sub-commands, delegate to `{app_name} --help`-style discovery is
    # intentionally omitted to keep the script dependency-free. Fall back to
    # returning no completions so PowerShell's default file-name completion
    # takes over.
    return @()
}}
"""


def _render_bash(app_name: str, commands: list[str]) -> str:
    joined = " ".join(commands)
    return f"""# {app_name} bash completion
_codegraphx_completion() {{
    local cur prev
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "{joined}" -- "$cur") )
    fi
    return 0
}}
complete -F _codegraphx_completion {app_name}
"""


def _render_zsh(app_name: str, commands: list[str]) -> str:
    joined = " ".join(commands)
    return f"""# {app_name} zsh completion
_codegraphx() {{
    local -a commands
    commands=({joined})
    _describe '{app_name} command' commands
}}
compdef _codegraphx {app_name}
"""


def _render_fish(app_name: str, commands: list[str]) -> str:
    lines = [f"# {app_name} fish completion"]
    for cmd in commands:
        lines.append(
            f"complete -c {app_name} -n '__fish_use_subcommand' -a '{cmd}'"
        )
    return "\n".join(lines) + "\n"
